import { supabase } from './supabase'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface Supplier {
  id: string
  name: string
  contact: string | null
  phone: string | null
  email: string | null
  address: string | null
  notes: string | null
  active: boolean
  created_at: string
  updated_at: string
}

export type POStatus = 'draft' | 'ordered' | 'partially_received' | 'received' | 'cancelled'

export interface PurchaseOrder {
  id: string
  po_number: string
  supplier_id: string | null
  store_id: string
  status: POStatus
  order_date: string | null
  expected_date: string | null
  notes: string | null
  created_at: string
  updated_at: string
  supplier?: { name: string } | null
  store?: { name: string; code: string } | null
  items?: PurchaseOrderItem[]
  created_by_user?: { full_name: string } | null
}

export interface PurchaseOrderItem {
  id: string
  po_id: string
  item_id: string
  qty_ordered: number
  qty_received: number
  unit_cost: number
  item?: { name: string; sku: string | null } | null
}

export interface SupplierFormData {
  name: string
  contact?: string
  phone?: string
  email?: string
  address?: string
  notes?: string
  active: boolean
}

export interface CreatePOData {
  supplierId?: string
  storeId: string
  orderDate?: string
  expectedDate?: string
  notes?: string
  items: { item_id: string; qty_ordered: number; unit_cost: number }[]
}

// ─── Suppliers ────────────────────────────────────────────────────────────────

export async function getSuppliers(): Promise<Supplier[]> {
  const { data, error } = await supabase
    .from('suppliers')
    .select('*')
    .order('name')
  if (error) throw new Error(error.message)
  return data as Supplier[]
}

export async function upsertSupplier(supplier: SupplierFormData & { id?: string }): Promise<Supplier> {
  const { data, error } = await supabase
    .from('suppliers')
    .upsert(supplier, { onConflict: 'id' })
    .select()
    .single()
  if (error) throw new Error(error.message)
  return data as Supplier
}

export async function deleteSupplier(id: string): Promise<void> {
  const { error } = await supabase.from('suppliers').delete().eq('id', id)
  if (error) throw new Error(error.message)
}

// ─── Purchase Orders ──────────────────────────────────────────────────────────

export async function getPurchaseOrders(storeId?: string, limit = 50): Promise<PurchaseOrder[]> {
  let query = supabase
    .from('purchase_orders')
    .select(`
      *,
      supplier:supplier_id (name),
      store:store_id (name, code),
      created_by_user:created_by (full_name),
      items:purchase_order_items(
        id, item_id, qty_ordered, qty_received, unit_cost,
        item:items(name, sku)
      )
    `)
    .order('created_at', { ascending: false })
    .limit(limit)

  if (storeId) query = query.eq('store_id', storeId)

  const { data, error } = await query
  if (error) throw new Error(error.message)
  return data as unknown as PurchaseOrder[]
}

export async function createPurchaseOrder(data: CreatePOData): Promise<string> {
  // 1. Insert PO
  const { data: po, error: poError } = await supabase
    .from('purchase_orders')
    .insert({
      supplier_id: data.supplierId || null,
      store_id: data.storeId,
      order_date: data.orderDate || null,
      expected_date: data.expectedDate || null,
      notes: data.notes || null,
      po_number: '', // auto-generated by trigger
    })
    .select('id')
    .single()

  if (poError) throw new Error(poError.message)

  // 2. Insert PO items
  const { error: itemsError } = await supabase
    .from('purchase_order_items')
    .insert(
      data.items.map(i => ({
        po_id: po.id,
        item_id: i.item_id,
        qty_ordered: i.qty_ordered,
        unit_cost: i.unit_cost,
      }))
    )

  if (itemsError) throw new Error(itemsError.message)
  return po.id
}

export async function updatePOStatus(poId: string, status: POStatus): Promise<void> {
  const { error } = await supabase
    .from('purchase_orders')
    .update({ status })
    .eq('id', poId)
  if (error) throw new Error(error.message)
}

export async function receivePurchaseOrder(
  poId: string,
  receivedItems: { po_item_id: string; qty_received: number }[],
  notes?: string
): Promise<void> {
  const { error } = await supabase.rpc('receive_purchase_order', {
    p_po_id: poId,
    p_received_items: receivedItems,
    p_notes: notes || null,
  })
  if (error) throw new Error(error.message)
}
