-- =============================================================================
-- Seed Stock Levels for All Active Items
-- =============================================================================
-- This is a template — no-op during migration. Run manually per store:
--
--   Replace <store_id> with your actual store UUID below.
--   This seeds all active items with qty = 0 for a single store.
--
--   INSERT INTO stock_levels (store_id, item_id, qty)
--   SELECT '<store_id>'::uuid, i.id, 0
--   FROM items i WHERE i.active = true
--   ON CONFLICT (store_id, item_id) DO NOTHING;
-- =============================================================================
DO $$ BEGIN /* no-op: manual seed template */ END; $$;
