-- Import historical expenses from CSV (Feb 15 - May 6, 2026)
-- Total: 261 expenses, Total amount: ৳1,619,765.60

DO $$
DECLARE
  v_store_id uuid;
BEGIN
  SELECT id INTO v_store_id FROM stores LIMIT 1;
  IF v_store_id IS NULL THEN
    RAISE EXCEPTION 'No store found';
  END IF;

  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-02-15', 'Noyon', 'Civil Works', 2000.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-02-15', 'Kamrul', 'Civil Works', 7000.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-02-15', 'Electrician Zidan', 'Electric Works', 2700.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-02-15', 'Tiles', 'Tiles', 1200.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-02-15', 'Hardware Store', 'Brick, Sand, Cement for Front Side renovation', 7810.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-02-15', 'Ananda Glass', 'Front Side Glass Panels and Doors', 48000.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-02-15', 'SK', 'Rack Color', 9000.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-02-15', 'Liton', 'Rack Works & Cleaning', 1500.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-01', 'Bahar', 'Glass Work Bahar Mistry', 11000.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-01', 'SK', 'Old Racks Paint Work', 10150.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-02', 'Display Nex BD', 'Gondola Racks - Black & Yellow', 189000.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-02', 'Nangolkot Electric', 'Lights', 9760.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-03', 'Nangolkot Electric', 'Weight Machine', 3800.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-04', 'Jahangir', 'Welding Works - Shutter Extension & Old Rack repair', 5000.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-05', 'Pintu', 'Lightbox Banner Printing & fitting', 7300.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-07', 'Relo', 'Banner Design', 4000.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-14', 'Nangolkot Electric', 'Lightbox Lights', 4900.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Seven Star', 'Deep Fridge', 45300.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Shofiq', 'Electrical Items', 2000.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Shopping Bag', 'Balloons', 1500.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-12', 'BPDB', 'Electric Bill', 1500.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Food', 'Iftaar', 3500.00, 'Cash', 'All Other Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Unilever', 'Personal Care - 131 Products', 134890.00, 'Bank transfer', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Olympic', 'Buiscuits & Cookies -29 Products', 15550.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Taaza', 'Tea & Coffee - 8 Products', 12830.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Godrej', 'Personal Care, Pest Control & Air Freshner 14 products', 9172.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Kaazi Farms', 'Cookies & Buiscuts', 5884.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Kellogs', 'Cereal - 10 Products', 13236.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-15', 'Zakaat Fund', 'Zakat Paid to Orphanage Kids', 4000.00, 'Cash', 'All Other Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-16', 'Dano', 'Dairy - 8 products', 8258.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-17', 'Betatech', 'CCTV + Monitor', 37500.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-18', 'Diploma', 'Powder Milk, Noodles & Buiscuit', 15577.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-18', 'Kellogs - FM Distribution', 'Cereals - 10 Products', 13236.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-19', 'DDN', 'Internet Bill 3 Months March - May 2026', 1950.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-20', 'Furniture Bazaar', 'Cash Table - Wooden', 6500.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-20', 'Computer', 'Router', 3300.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-20', 'Shofiq', 'Electrical Items', 2375.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-20', 'Berger', 'Color', 15000.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-20', 'Miscellenous', 'Miscellenous Expenses', 2000.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-20', 'Chittagong Cleaners', 'Deep Cleaning & Pest Control', 8500.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-03-31', 'BPDB', 'Electric Bill', 1000.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-02', 'Meridian', 'Chips & Sauce', 2026.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-02', 'Square Toiletries', 'Sanitary Pads & Pampers', 8219.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-02', 'Bashundhara', 'Tissue', 9429.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-03', 'Belgian Glass', 'Glass Frame for Rice & Grain display - advance', 10000.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-03', 'Pickup', 'Pahartoli to Chawkbazar', 1650.00, 'Cash', 'Transport & Conveyance');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-03', 'SM Enterprise', 'Rice & Grain', 113300.00, 'Bank transfer', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-03', 'Mim Enterprise', 'Rice & Grain', 51713.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-04', 'Starship - Tarin Enterprise', 'Batch01 - Juice & Cookies', 1450.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-03', 'Staff', 'Bed & Pillow for Mannan', 1500.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-04', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-03', 'SK', 'Front Side Painting', 3300.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-03', 'Paint Shop', 'Front Side Paints', 2300.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-04', 'Square Food & Beverages', 'Spices & Oil 55 items', 26000.00, 'Bank transfer', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-05', 'Belgian Glass', 'Glass Frame for Rice & Grain display', 11150.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-05', 'Pahartali', 'Egg Tray - 9 pc', 147.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-05', 'Pahartali - EGG', 'Egg 270 pc', 2253.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-05', 'Tang/Cadbury', 'Chocolates & Tang 15 Items', 16320.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-05', 'Starship', 'Milkshake, chanachur, chewing gum', 1450.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-05', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-06', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-07', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-06', 'Marks - Bismillah Enterprise', 'Milk Powder & Tea', 8719.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-06', 'Rupchanda', 'Oil', 22380.00, 'Bank transfer', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-06', 'Maggi', 'Noodles 24pc', 1449.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-06', 'Pran Agro Limited', 'Sauce 7pc', 1074.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-07', 'Nestle - M/S Army', 'Chocolates & Juice 16 items', 10161.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-07', 'Meridian', 'Chips & Snacks', 1925.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-07', 'ACI', 'Air Freshener & Mosquito Spray', 2720.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-07', 'Bombay Sweets', 'Batch01 - Chips, Chanachur etc', 3093.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-07', 'Rupchanda', 'Batch02 - Oil', 9072.00, 'Bank transfer', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-07', 'BPDB', 'Electric Bill', 1500.00, 'Bank transfer', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-07', 'Store Expense', 'Tally Khata, belacha etc', 660.00, 'Cash', 'All Other Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-07', 'Ahmed', 'Soy Sauce & Vinegar', 975.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'Aarong', 'Milk - 20kg', 1810.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'Prestige Bengal Ltd.', 'Olive Oil & Talcum Powder', 7038.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'Hithium', '5 pc Hithium HeroEE1', 120020.00, 'Bank transfer', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'FM Distribution', 'Baby Oats, Safari, etc', 4415.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'Body Wash', 'Body Wash 4 pc', 770.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'Eggs', '510 eggs @7.10/pc', 3825.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'Bokkor Milk', '10L', 900.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'Bashundhara', 'Batch02 - Tissue', 390.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'M Network Ltd', 'Olive Oil 3 pc', 1200.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-09', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-08', 'Mojo', 'Batch01', 1290.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-09', 'Abhay Distribution', 'Colgate & Gillette', 5888.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-09', 'Mat', 'Mat for Store', 620.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-09', 'Starship - Tarin Enterprise', 'Batch02 - Mango & Chocolate Milk', 2448.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-09', 'KGM Enterprise', 'Baking Products', 7153.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-09', 'Mannan', 'Bucket, etc', 620.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-09', 'Igloo', 'Ice-cream', 13474.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-10', 'Transtec', 'Lights', 4641.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-10', 'Kaazi Farms', 'Batch02 - Jam', 735.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-10', 'Kohinoor Chemical', 'Sandalina Soap & Tibbet', 2964.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-10', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-11', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-12', 'Savoy', 'Ice-cream', 6986.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-12', 'Electrical Equipmnets', 'HIthiium Battery Installation Wires and others', 1840.00, 'Bank transfer', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-12', 'Mim Enterprise', 'Onions, Potatoes etc', 15926.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-12', 'Kabir Showdagor Store', 'Coconut', 2680.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-12', 'CNG', 'Pahartoli to Chawkbazar', 300.00, 'Cash', 'Transport & Conveyance');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-12', 'Keya', 'Mustard Oil - 5L', 1150.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-12', 'Mannan', 'Snacks', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-12', 'Bokkor Milk', 'Milk 10L', 900.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-12', 'PaiMart', 'Imported Products + 400 tk Delivery Charge', 15311.00, 'Bkash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-12', 'Sumi Akter', '510 eggs', 4660.00, 'Bank transfer', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-13', 'Pusti', 'Cooking Needs', 19588.00, 'Bank transfer', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-13', 'Nestle - Hoque & Sons', 'Coffee, Baby Care foods, etc', 26010.00, 'Bank transfer', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-13', 'Olympic', 'Buiscuits', 3451.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-13', 'Meghna', 'Fresh Water 250-1L', 1130.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-13', 'Cash', 'Tahsin', 100.00, 'Cash', 'Partners Take');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-13', 'Electric Mechaninc', 'Hithiium Battery Installation', 1500.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'BPDB', 'Electric Bill', 1500.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-13', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-13', 'Abhay Distribution', 'Osaka Tape, Fevicol, Eraser, Pencil etc', 2140.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'Bokkor Milk', 'Milk 10L', 900.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'Bismillah Trading Chips', 'Chips - Lays', 5842.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'Square', 'Cake, Pickles etc', 4518.00, 'Bank transfer', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'Drinko/Frooto', 'Juice', 1320.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'Lunch', 'Ansar', 200.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'SS Trade International', 'Teer Atta', 1003.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'Ames', 'Fuchka', 210.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'Olympic', 'Funday, buiscuits etc', 498.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'Hoque', 'Buiscuit', 420.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-14', 'Kaazi Farms', 'Dry Cake/Popocorn', 1620.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-15', 'GHUSH', 'Hijra', 300.00, 'Cash', 'All Other Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-15', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-15', 'FM Distribution', 'Buiscuits Lexus', 5212.00, 'Bkash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-15', 'Mannan', 'April Half Salary', 5000.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-16', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-16', 'Savoy', 'Ice-cream', 9534.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-16', 'Ali Express', 'Barcode Printer, POS Printer, Barcode Scanner', 15000.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-16', 'Snacks', 'Mannan', 100.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-16', 'Bag', 'Polythene Bag', 120.00, 'Cash', 'All Other Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-17', 'Food', 'Mannan', 200.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-18', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-18', 'Bokkor Milk', '10L', 820.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-18', 'Partners Take', 'Tahsin', 2000.00, 'Cash', 'Partners Take');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-18', 'Eggs', '500pc 10.20', 5300.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-19', 'Kishwan', 'Buiscuits', 830.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-19', 'FM Distribution', 'Safari Chocolates', 1728.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-19', 'Olympic', 'Toffee', 393.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-19', 'Cocacola', 'Fridge Installation', 500.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-19', 'Aarong', 'Butter', 662.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-19', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-20', 'Nestle', 'Baby Care Products', 2028.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-20', 'Aarong', 'Butter 3p 200g + Yoghurt', 1047.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-20', 'Bokkor Milk', 'Cash Paid', 900.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-20', 'Pran Translinc Distribution', 'Pampers & Others', 6782.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-20', 'Bag', 'Polythene Bag', 360.00, 'Cash', 'All Other Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-20', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-20', 'Tablet', 'Sanmar', 16500.00, 'Bank transfer', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-21', 'Aarong', 'Matha, Lacchi', 590.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-21', 'Kaazi Farms', 'Cake, Pickles etc', 200.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-21', 'Lily', 'Soap & Bodywash', 2340.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-21', 'Bombay Sweets', 'Chips', 682.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-21', 'Cocacola', 'Coke, Sprite, Fanta 2 case each all size', 14568.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-21', 'Paragon', 'Parathas and Ghee', 4580.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-21', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-22', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-22', 'Haque', 'Mr. Cookies Buscuits', 256.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-22', 'Nahar Agro', 'Milk & Yoghurt', 1005.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-22', 'Pitstop', 'Bread & Buns', 1258.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-22', 'Mizan', 'Partnership Deed', 3000.00, 'Bkash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-22', 'Mobile Recharge', 'April', 1000.00, 'Bkash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-22', 'Mim Enterprise', 'Spices & Nuts etc', 19000.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-22', 'East Baker', '20 pieces', 265.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-22', 'Ansar', 'ansar', 1480.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-23', 'Aarong', 'Sliced Cheese', 909.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-23', 'Bokkor Milk', '10L', 900.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-23', 'Fulkoli', 'Biscuits & Toasts', 3028.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-23', 'Eggs', '1000 eggs', 10400.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-23', 'Tahsin', 'partners take', 200.00, 'Cash', 'Partners Take');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-23', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-24', 'Bokkor Milk', '10L', 900.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-24', 'BOSS COIL', 'for store use', 50.00, 'Cash', 'All Other Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-24', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-24', 'BPDB', 'Electric Bill', 2000.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-24', 'Islam (Mama)', 'Mohish er Doi', 2250.00, 'Bkash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-25', 'Olympic', 'Chocolate - funday', 256.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-25', 'Aarong', 'Yoghurt', 208.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-25', 'Kohinoor Chemical', 'Soap & Bodywash', 846.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-25', 'Bokkor Milk', '10L', 900.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-25', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-25', 'Mechanic', 'Fan Installation', 500.00, 'Cash', 'Utility Expenses');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-25', 'Pusti', 'Coffee mix, tea, milk powder', 1913.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-26', 'Teer', 'Oil', 3474.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-26', 'Starship', 'Juice', 1452.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-26', 'Pusti', 'Oil 5L', 12000.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-26', 'Parachute', 'Hair Oil', 388.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-26', 'KGM Enterprise', 'Keya Muri', 665.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-26', 'Mishti Lonka', 'Homemade Masala', 1280.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-26', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-26', 'Mim Enterprise', 'Rice, Onion, Potatoes, Garlic etc', 33214.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-27', 'Bismillah Family Food', 'Frozen Samosa 2 pc', 260.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-27', 'Haque & Sons', 'Cerelac, Nido 3pc', 980.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-27', 'Abu Bakar & Co', 'Cup Noodles (24pc)', 172.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-27', 'Fulkoli', 'Chanachur and biscuits', 490.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-27', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-27', 'Bokkor Milk', '10L', 900.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-28', 'Pit Stop', 'Bread & Buns', 844.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-28', 'SR Trade', 'Sun Chips', 330.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-28', 'Hijra', 'chanda', 20.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-28', 'Tahsin', 'partners take', 1200.00, 'Cash', 'Partners Take');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-28', 'Bokkor Milk', '10L', 900.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-28', 'Snacks', 'Mannan', 100.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-29', 'Fresh', 'Aata, Sugar, Milk Powder', 5240.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-29', 'Khedman', 'Bit Lobon (salt), baking soda', 360.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-29', 'Cocacola', 'Sprite - 4 cases', 2180.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-29', 'FM Distribution', 'Oats Bar 6pcs', 1680.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-29', 'Nahar Agro', 'Milk', 488.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-29', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-29', 'Bismillah Enterprise', 'Marks Powder Milk (24 pcs)', 7470.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-30', 'Olympic', 'Biscuits & Toasts', 903.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-30', 'Tahsin', 'partners take', 30.00, 'Cash', 'Partners Take');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-30', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-04-30', 'Bokkor Milk', '15L', 1350.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-01', 'Ali Express', 'Postal Office tax 950*2', 1990.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-01', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-02', 'Pitstop', 'Bread 10pc', 697.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-02', 'Pran Agro Limited', 'Pran Ice Bar 4 Packs', 168.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-02', 'Ispahani', 'Tea', 1765.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-02', 'Starship', 'Condensed Milk 4pc', 360.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-02', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-02', 'Tahsin', 'partners take', 1020.00, 'Cash', 'Partners Take');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-02', 'Aarong', 'Yoghurt, Lassi', 553.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-03', 'Tarin Enterprise', 'Starship Juice', 975.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-03', 'Drinko', 'Juice', 600.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-03', 'Abu Bakar & Co', 'MAMA Noodles 8pc', 640.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-03', 'Fulkoli', 'Toast', 495.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-03', 'Smart Corporation', 'Pusti Atta, Moida', 1932.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-03', 'Tylox', 'Tylox & Facewash', 1044.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-03', 'Bismillah Family Food', 'Frozen Snacks', 890.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-03', 'Bokkor Milk', '10L', 900.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-03', 'Tahsin', 'Partners Take', 110.00, 'Cash', 'Partners Take');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-03', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-04', 'KGM Enterprise', 'Brown Sugar, Shorisha Oil', 3495.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-04', 'Haque & Sons', 'Nan Optipro 4pc', 3076.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-04', 'Ahmed', 'Pickles and Sauce', 1430.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-04', 'Square', 'Washi Powder, Tooth powder, shampoo, Zero Cal Drinks 2p', 2968.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-04', 'Paragon', 'Family Paratha 20pc 6pcs', 1593.60, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-04', 'Tahsin', 'Partners Take', 60.00, 'Cash', 'Partners Take');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-04', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-04', 'Trade License', 'Final Payment', 6000.00, 'Cash', 'Capital Expenditure');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-04', 'Bokkor Milk', '15L', 1800.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-04', 'Islam Trading', 'Dano Milk Powder', 2765.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'Pitstop', 'Bread & Buns', 1653.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'Dabur', 'Honey, Toothpaste, Hair Oil Vatika', 6754.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'Kaazi Farms', 'Toast Biscuits (Damage Return 432taka)', 40.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'AS Enterprise', 'Nutella 3pc, Kinder Joy, Tictac', 6000.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'Marks - Bismillah Enterprise', 'Marks Powder Milk', 1509.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'Bismillah Trading', 'Kurkure, Lays, Oats, Magic Masala', 4654.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'Paragon', 'Low Fat Paratha 6 pcs', 1220.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'Abhay Distribution', 'Sensodyn Toothpaste, Eno, Marker pen, custard oil, colgate', 5526.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'Square', 'Chanachur, daal, sauce, pickles', 3044.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'Aarong', 'Yoghurt, Labaang. Matha', 752.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'ACI', 'Brown Sugar 10 pc', 1200.00, 'Cash', 'Stock Purchase');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-05', 'Snacks', 'Mannan', 50.00, 'Cash', 'Staff salary');
  INSERT INTO expenses (store_id, expense_date, vendor_name, description, amount, payment_type, category) VALUES (v_store_id, '2026-05-06', 'BPDB', 'Electric Bill', 2000.00, 'Cash', 'Utility Expenses');

  RAISE NOTICE 'Imported 261 expenses successfully';
END $$;
