-- =============================================================================
-- Inventory Import from CSV: Lucky Store Inventory with images
-- =============================================================================
-- This is a manual import template — no-op during migration.
-- To use it:
--   1. Create temp table: CREATE TEMP TABLE temp_inventory_import (...)
--   2. Load CSV data via Supabase dashboard or psql
--   3. Uncomment and run the sections below
--   4. Clean up: DROP TABLE IF EXISTS temp_inventory_import;
-- =============================================================================
DO $$ BEGIN /* no-op: manual CSV import template */ END; $$;
